# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
      - link: "pgsql:postgres:password@tcp(127.0.0.1:5432)/postgres"
        tables: "balance, price"
        descriptionTag: true
        noModelComment: true
