// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalPriceDao is internal type for wrapping internal DAO implements.
type internalPriceDao = *internal.PriceDao

// priceDao is the data access object for table price.
// You can define custom methods on it to extend its functionality as you wish.
type priceDao struct {
	internalPriceDao
}

var (
	// Price is globally public accessible object for table price operations.
	Price = priceDao{
		internal.NewPriceDao(),
	}
)

// Fill with you ideas below.
